language: python
dist: trusty
sudo: required

python:
- '3.5'

before_install:
- pip install -U pip
- pip install -U setuptools
- pip install -r requirements.txt
- pip install tox

script:
- tox
- make html

after_success:
- rm -rf .git/
- git init
- git config user.name "Travis CI"
- git config user.email "travis@domain.com"
- git config --global push.default simple
- git remote add origin https://${GITHUB_TOKEN}@github.com/surabaya-py/surabaya-py.github.io
- make github